@hostname = http://localhost:10000

GET {{hostname}}/accounts/activeAccounts
###
GET {{hostname}}/accounts/:accountId/collections
###
GET {{hostname}}/accounts/:accountId/songs
###
GET {{hostname}}/collections/empty
###
GET {{hostname}}/collections/:collectionId/songs
###
GET {{hostname}}/songs
###
GET {{hostname}}/songs/:songId/collections