version: '3.8'
services:
  db:
    image: postgres:alpine3.16
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_DB:-database}
      - POSTGRES_USER=${DATABASE_USER:-admin}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password}
    ports:
      - ${DATABASE_PORT:-5432}:5432
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local